name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/**.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    if: startsWith(github.event.head_commit.message, 'Release') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel cffi

      - name: Fix distutils for Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade setuptools==58.2.0  # Known stable version with distutils
      
      - name: Install MSVC Build Tools (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install visualstudio2019buildtools --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      - name: Build and test wheels
        env:
          CIBW_ARCHS: "auto64"
          CIBW_SKIP: "cp36-* cp37-* cp38-* pp37-* pp38-* pp310-*"
          CC: clang
          CIBW_BEFORE_BUILD: "pip install --upgrade setuptools wheel"
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Save Wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
